### ISSUE TITLE
Instructions for macOS

### ISSUE THREAD

**Issue by tarcisioefb** [3rl-io/spidgets-3dof#1]
First of all, thank you so much @kkota1!
I really want to use this 3DoF dashboard with my Rokid Max, but I'm struggling in the Terminal, I imagine it's because I'm on a macOS arm64. I can create the server, but without 3DoF.
Is it possible to create a specific guide for macOS (considering Macs with Apple Silicon)?

**Comment by kkota1** [comment]
Sorry for the inconvenience. Have you tried with `sudo`? That fixed it for a couple of people because the OS needs permission to communicate with USB devices

So `sudo ./bin/ar-server` if you're using the pre-built file or `sudo bun ar-server.js` if you're running it manually

If that doesn't work, maybe we can hop on a discord call because I don't have a Mac to test with atm

**Comment by kkota1** [comment]
The readme now has separate instructions per OS type

Commit: https://github.com/3rl-io/spidgets-3dof/commit/82211e2484cbbf562c1669936c70127e474bc2ba
